<?php

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\views\Views;
/**
 * Implements hook_preprocess_html().
 */

function indbase_preprocess_html(&$variables) {
  $alias = \Drupal::service('path_alias.manager')
    ->getAliasByPath(\Drupal::service('path.current')->getPath());

  if ($alias === '/GST-LAW' || $alias === '/help/statevat') {
    $variables['attributes']['class'][] = 'gst-law-page';
  }
}
